syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";

message C_LOGIN
{

}

message S_LOGIN
{
	bool success = 1;
}

message C_ENTER_GAME
{

}

message S_ENTER_GAME
{
	bool success = 1;
	ObjectInfo player = 2;
}

message C_LEAVE_GAME
{

}

message S_LEAVE_GAME
{

}

message S_SPAWN
{
	repeated ObjectInfo objects = 1;
}

message S_DESPAWN
{
	repeated uint64 object_ids = 1;
}

message C_MOVE
{
	uint64 timestamp = 1;
	PosInfo info = 2;
}

message S_MOVE
{
	uint64 timestamp = 1;
	PosInfo info = 2;
}

message C_PING
{
	uint64 send_tick = 1;
}

message S_PONG
{
	uint64 send_tick = 1;
}

message C_LOG_POS
{
	uint64 timestamp = 1;
	bool is_my_player = 2;
	SyncMode sync_mode = 3;
	PosInfo info = 4;
}

message C_SIMULATE_START
{
}

message S_SIMULATE_START
{
	uint64 object_id = 1;
}

message C_SIMULATE_FINISH
{
}

message S_SIMULATE_FINISH
{
	uint64 object_id = 1;
}